### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by spences10** [spences10/characters-from-password#26]
I have made a bit of a mess with the styled components and it's not great on a smaller screen.

I have found an example of using CSS grid with styled-components here: https://medium.com/styled-components/how-to-create-responsive-ui-with-styled-components-c6b71a3ce172

**Comment by Mist12345** [comment]
Hey spences, I thought I could help you out with this but I can't seem to get the project up and running. I was expecting to see a HTML file when I forked the project. Any help would be great.

**Comment by spences10** [comment]
Hi @Mist12345 thanks for taking a look.

What was it you were having issues with? I made this in [Next.js](https://github.com/zeit/next.js) so all you need to run the project is a functioning [Node.js](https://nodejs.org/en/) installation then, from terminal:

```bash
yarn install # or npm install
yarn dev # or npm run dev
```

The `index.html` is generated (I presume) by Next.js at runtime

The styling is in [styled-components](styled-components.com) I made a real mess with it all so need to get some media queries in there to cater for the smaller screen sizes.

Thanks

**Comment by Mist12345** [comment]
So, I've made it responsive! Looks pretty good. However I can't figure out how to get my local fork to update so I can compare the changes and create a pull request..

**Comment by spences10** [comment]
Hey @Mist12345 take a look at [this](https://github.com/spences10/cheat-sheets/blob/master/git.md#create-a-pr-pull-request) which I put together for my own reference after fumbling through it a few times.

Looking at your fork you don't seem to have pushed your changes to your branch either.

I'd suggest first pushing your changes to your branch first then you will be prompted by GitHub to make a pull request and compare the changes there.

**Comment by Mist12345** [comment]
OMG I got it!! Your page is exactly what Googling it gave me tbh turns out I had the origin and upstream reversed then I just had to push the changes. It's pull request #30. Thanks for the help.

**Comment by spences10** [comment]
Closed with c7b7b7bc3d2d8d7b95d2ed6e5cf86f2d3dece025
